### ISSUE TITLE
Modular application load system

### ISSUE THREAD

**Issue by yuxuanchiadm** [McKay42/McEngine#22]
To implements this. We need:

1. Implements modular application load system using dynamic link library(dll and so). (Create new issue, branch needed)
2. Exports engine API to single project. (Create new issue, branch needed)
3. Simple documention and example projects. (Just convert FrameworkTest?)
4. Any Idea.

Why:

1. Because it's cool XD!
2. Let update Engine for App more simpler.
3. Low coupling in general a good idea.

Risk:

1. Break current things. (This should be fine for now)
2. Probably waste time.
3. More bugs and fun XD.

Note:
Should be low priority for now because we need focus on McOsu first.

**Comment by McKay42** [comment]
When the time comes, this issue will have to be split into multiple smaller ones anyway, up until then it doesn't have to exist.

From now on I'll enforce "Don't create issues unless you also work on them or fix them yourself" in this repository.
